bucket_name: "enter-bucket-name"
inbount_bucket_key: "anantha-subramanian/Inbound/"
preprocessor_bucket_key: "anantha-subramanian/pre-processed/"
preprocessed_infy_bucket_key: "anantha-subramanian/pre-processed/INFY/INFY.xls"
preprocessed_sbin_bucket_key: "anantha-subramanian/pre-processed/SBIN/SBIN.csv"
preprocessed_infy_csv_bucket_key: "anantha-subramanian/pre-processed/INFY/INFY.csv"
standardized_bucket_key_infy: "s3://enter-bucket-name/anantha-subramanian/Standardized/INFY/"
standardized_bucket_key_sbin: "s3://enter-bucket-name/anantha-subramanian/Standardized/SBIN/"
landing_infy_loc: "s3://enter-bucket-name/anantha-subramanian/Landing/INFY/"
landing_sbin_loc: "s3://enter-bucket-name/anantha-subramanian/Landing/SBIN/"
indicator_file_loc: "s3://enter-bucket-name/anantha-subramanian/indicator.txt"
infy_loc_inbound: "s3://enter-bucket-name/anantha-subramanian/Inbound/INFY/INFY.xls"
sbin_loc_inbound: "s3://enter-bucket-name/anantha-subramanian/Inbound/SBIN/SBIN.csv"
sbin_loc_landing_key: "anantha-subramanian/Landing/SBIN/SBIN.csv"
infy_loc_landing_key: "anantha-subramanian/Landing/INFY/INFY.csv"
standard_loc: "s3://enter-bucket-name/anantha-subramanian/Standardized/"
s3_landing_infy: "s3://enter-bucket-name/anantha-subramanian/Landing/INFY/INFY.csv"
s3_landing_sbin: "s3://enter-bucket-name/anantha-subramanian/Landing/SBIN/SBIN.csv"
infy_loc_csv: "s3://enter-bucket-name/anantha-subramanian/Inbound/INFY/INFY.csv"
sbin_loc_csv: "s3://enter-bucket-name/anantha-subramanian/Inbound/SBIN/SBIN.csv"
schema_file: "s3://enter-bucket-name/anantha-subramanian/code/schema.txt"
counter_file: "s3://enter-bucket-name/anantha-subramanian/counter.json"
indicator_key_infy: "anantha-subramanian/pre-processed/INFY/indicator.txt"
indicator_key_sbin: "anantha-subramanian/pre-processed/SBIN/indicator.txt"
outbound_key: "s3://enter-bucket-name/anantha-subramanian/Outbound/"
archive_key: "s3://enter-bucket-name/anantha-subramanian/Archive/"
counter_file_path_infy: "anantha-subramanian/pre-processed/INFY/counter.json"
counter_file_path_sbin: "anantha-subramanian/pre-processed/SBIN/counter.json"


